using System;

namespace RealtimeCSG.Foundation
{
	/// <summary>Stores a mesh generated by calling <see cref="RealtimeCSG.Foundation.CSGTree.GetGeneratedMesh" />.</summary>
	/// <remarks>See the [Create Unity Meshes](~/documentation/createUnityMesh.md) article for more information. <see cref="RealtimeCSG.Foundation.GeneratedMeshContents"/> holds the binary mesh data from the managed side and can be turned into a [UnityEngine.Mesh](https://docs.unity3d.com/ScriptReference/Mesh.html) by calling <see cref="RealtimeCSG.Foundation.GeneratedMeshContents.CopyTo" />.
	/// See the [Create Unity Meshes](~/documentation/createUnityMesh.md) article for more information.</remarks>
	/// <seealso cref="RealtimeCSG.Foundation.CSGTree" /><seealso cref="RealtimeCSG.Foundation.CSGTree.GetGeneratedMesh" />
	/// <seealso cref="RealtimeCSG.Foundation.GeneratedMeshDescription"/><seealso cref="RealtimeCSG.Foundation.SurfaceDescription"/>
	/// <seealso href="https://docs.unity3d.com/ScriptReference/Mesh.html">UnityEngine.Mesh</seealso>
	[Serializable]
	public sealed class GeneratedMeshContents
	{
		/// <value>Describes the GeneratedMesh.</value>
		/// <remarks>This is a copy of the description used to retrieve the GeneratedMeshContents by calling <see cref="RealtimeCSG.Foundation.CSGTree.GetGeneratedMesh" />.</remarks>
		public GeneratedMeshDescription description;

		/// <value>Triangle indices to the vertices that make up the triangle.</value>
		public int[]		indices;
		
		/// <value>Position for each vertex.</value>
		public UnityEngine.Vector3[]	positions;
		
		/// <value>Tangent for each vertex.</value>
		/// <remarks><note>Can be null when the <see cref="description"/> has no tangents set in its <see cref="RealtimeCSG.Foundation.MeshQuery.UsedVertexChannels"/>.</note></remarks>
		public UnityEngine.Vector4[]	tangents;
		
		/// <value>Normal for each vertex.</value>
		/// <remarks>Each <seealso cref="RealtimeCSG.Foundation.BrushMesh.Polygon"/> has a <seealso cref="RealtimeCSG.Foundation.SurfaceDescription.smoothingGroup"/> field in its <seealso cref="RealtimeCSG.Foundation.SurfaceDescription"/>.
		/// If the <seealso cref="RealtimeCSG.Foundation.SurfaceDescription.smoothingGroup"/> is set to something other than 0 the normal is calculated by; combining the normals of all the surfaces around each vertex that share the same <seealso cref="RealtimeCSG.Foundation.SurfaceDescription.smoothingGroup"/>.
		/// If the <seealso cref="RealtimeCSG.Foundation.SurfaceDescription.smoothingGroup"/> is set to 0 the normal of the polygon is used.
		/// <note>Can be null when the <see cref="description"/>  has no normals set in its <see cref="RealtimeCSG.Foundation.MeshQuery.UsedVertexChannels"/>.</note>
		/// </remarks>
		public UnityEngine.Vector3[]	normals;

		/// <value>First uv channel for each vertex.</value>
		/// <remarks>These are created by multiplying the vertices of the <seealso cref="RealtimeCSG.Foundation.BrushMesh"/>, which was used to generate this geometry, 
		/// by the <seealso cref="RealtimeCSG.Foundation.SurfaceDescription.UV0" /> <seealso cref="RealtimeCSG.Foundation.UVMatrix"/> of the <seealso cref="RealtimeCSG.Foundation.SurfaceDescription"/> of the vertex.
		/// <note>Can be null when the <see cref="description"/> has no <seealso cref="RealtimeCSG.Foundation.VertexChannelFlags.UV0" /> set in its <see cref="RealtimeCSG.Foundation.MeshQuery.UsedVertexChannels"/>.</note>
		/// </remarks>
		public UnityEngine.Vector2[]	uv0;

		/// <value>Bounds of the mesh.</value>
		public UnityEngine.Bounds       bounds;

		/// <summary>Copies the contents of the generated mesh to a [UnityEngine.Mesh](https://docs.unity3d.com/ScriptReference/Mesh.html).</summary>
		/// <param name="mesh">The mesh to copy the <see cref="RealtimeCSG.Foundation.GeneratedMeshContents"/> into</param>
		/// <remarks><code>
		/// MeshDescription meshDescription = ... ;
		/// GeneratedMeshContents contents = tree.GetGeneratedMesh(meshDescription);
		/// UnityEngine.Mesh unityMesh = new UnityEngine.Mesh();
		/// contents.CopyTo(unityMesh);
		/// </code>
		/// See the [Create Unity Meshes](~/documentation/createUnityMesh.md) article for more information.
		/// </remarks>
		/// <exception cref="System.ArgumentNullException">Thrown when <paramref name="mesh"/> is null.</exception>
		/// <exception cref="System.ArgumentException">Thrown when <paramref name="mesh"/> is invalid. This can happen when the mesh has already been destroyed.</exception>
		public void CopyTo(UnityEngine.Mesh mesh)
		{ 
			if (object.ReferenceEquals(mesh, null))
				throw new ArgumentNullException("mesh");
			if (!mesh)
				throw new ArgumentException("mesh", "mesh is not valid, it might've already be destroyed");

			if (description.vertexCount < 3 ||
				description.indexCount < 3)
			{
				mesh.Clear();
				return;
			}
			
			mesh.vertices = positions;
			if (normals  != null) mesh.normals	= normals;
			if (tangents != null) mesh.tangents	= tangents;
			if (uv0      != null) mesh.uv		= uv0;
			
			mesh.SetTriangles(indices, 0, calculateBounds: true);
			//mesh.bounds = bounds;
		}
	};
}